name: Buscript
main: buscript.BuscriptPlugin
version: maven-version-number
author: dumptruckman
softdepend: [Vault]

commands:
  run:
    description: reloads script file and config
    usage: /<command> <script> [player]
    permission: buscript.run

permissions:
  buscript.run:
    default: OP